version: "3.11.6"

services:
  db:
    image: postgres:16.0
    env_file:
      - ./backend/.env.test
    ports:
      - 5432:5432
    networks:
      - app_network

networks:
  app_network:
    driver: bridge